apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: izvoli-si
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: izvoli-si
    newName: rg.fr-par.scw.cloud/djnd/izvoli-si
    newTag: 'daa673c48c51fb06655729923291b2897c687dff'
