apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: izvoli-si
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: izvoli-si
    newName: rg.fr-par.scw.cloud/djnd/izvoli-si
    newTag: '7802302b747cae5476a5de44ad0cb4f5b352f660'
