apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: izvoli-si
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: izvoli-si
    newName: rg.fr-par.scw.cloud/djnd/izvoli-si
    newTag: '4f7d60f125251cbf85163283280323f3ab1b1329'
