apiVersion: v1
kind: Secret
metadata:
  name: novdan-secrets
type: Opaque
stringData:
  DJANGO_DEBUG: ""
  DJANGO_SECRET_KEY: "secret-key"
  DJANGO_DATABASE_HOST: "db-host"
  DJANGO_DATABASE_NAME: "db-name"
  DJANGO_DATABASE_USERNAME: "db-username"
  DJANGO_DATABASE_PASSWORD: "db-password"
  DJANGO_ENABLE_S3: ""
  DJANGO_AWS_ACCESS_KEY_ID: "access-key-id"
  DJANGO_AWS_SECRET_ACCESS_KEY: "secret-access-key"
  DJANGO_AWS_STORAGE_BUCKET_NAME: "bucket-name"
  DJANGO_AWS_LOCATION: "location"
  DJANGO_SENTRY_URL: "sentry-url"
