volumes:
  postgres-data:

services:
  izvoli:
    build:
      context: ./izvoli
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - VITE_API_URL_BASE=http://localhost:8000/api
    volumes:
      - ./izvoli/public:/app/public:delegated,rw
      - ./izvoli/src:/app/src:delegated,rw
      - ./izvoli/.prettierrc.json:/app/.prettierrc.json:delegated,rw
      - ./izvoli/eslint.config.js:/app/eslint.config.js:delegated,rw
      - ./izvoli/index.html:/app/index.html:delegated,rw
      - ./izvoli/jsconfig.json:/app/jsconfig.json:delegated,rw
      - ./izvoli/vite.config.js:/app/vite.config.js:delegated,rw
