# Generated by Django 4.2 on 2024-04-17 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Ime')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Volitve',
                'verbose_name_plural': 'Volitve',
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, verbose_name='Ime')),
                ('finished_quiz', models.BooleanField(default=False, verbose_name='Je oddal_a vprašalnik? (se izpolni avtomatsko)')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.election', verbose_name='Volitve')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Uporabnik')),
            ],
            options={
                'verbose_name': 'Stranka',
                'verbose_name_plural': 'Stranke',
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Izjava')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Dodaten opis')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.election', verbose_name='Volitve')),
            ],
            options={
                'verbose_name': 'Izjava',
                'verbose_name_plural': 'Izjave',
            },
        ),
        migrations.CreateModel(
            name='StatementGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name': 'Skupina',
                'verbose_name_plural': 'Skupine',
            },
        ),
        migrations.CreateModel(
            name='StatementAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(choices=[('YES', 'DA'), ('NO', 'NE'), ('NEUTRAL', 'NEOPREDELJENO')])),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Obrazložitev')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.party', verbose_name='Stranka')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parties.statement', verbose_name='Izjava')),
            ],
            options={
                'verbose_name': 'Odgovor',
                'verbose_name_plural': 'Odgovori',
            },
        ),
        migrations.AddField(
            model_name='statement',
            name='statement_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parties.statementgroup', verbose_name='Skupina izjav'),
        ),
        migrations.AddConstraint(
            model_name='statementanswer',
            constraint=models.UniqueConstraint(fields=('party', 'statement'), name='unique_party_statement'),
        ),
    ]
