# Generated by Django 4.2 on 2024-04-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementanswer',
            name='answer',
            field=models.TextField(blank=True, choices=[('YES', 'DA'), ('NO', 'NE'), ('NEUTRAL', 'NEOPREDELJENO')]),
        ),
    ]
