# Generated by Django 4.2 on 2024-04-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_alter_statementanswer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statementanswer',
            name='answer',
            field=models.TextField(blank=True, choices=[('YES', 'DA'), ('NO', 'NE'), ('NEUTRAL', 'NEOPREDELJENO')], null=True),
        ),
        migrations.AlterField(
            model_name='statementanswer',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Obrazložitev'),
        ),
    ]
