# Generated by Django 4.2 on 2024-04-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_alter_statementanswer_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Slika'),
        ),
    ]
