# Generated by Django 4.2 on 2024-05-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0004_party_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='hide_in_app',
            field=models.BooleanField(default=False, verbose_name='Vprašanja ne prikazuj na aplikaciji izvoli.eu'),
        ),
    ]
