# Generated by Django 4.2 on 2024-05-08 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0006_party_votematch_id_statement_votematch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='tag',
            field=models.TextField(blank=True, default='', verbose_name='Oznaka'),
        ),
    ]
