apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: izvoli
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    # for more ciphers
    nginx.ingress.kubernetes.io/ssl-ciphers: "ALL:!aNULL:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv2:+EXP"
    # nginx.ingress.kubernetes.io/ssl-prefer-server-ciphers: "false"
    # nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - izvoli-eu.lb.djnd.si
        - izvoli.eu
      secretName: izvoli-tls
  rules:
    - host: izvoli-eu.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: izvoli
                port:
                  number: 8000
    - host: izvoli.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: izvoli
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: izvoli-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*" # TODO
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - files.izvoli-eu.lb.djnd.si
        - files.izvoli.eu
      secretName: izvoli-nginx-tls
  rules:
    - host: files.izvoli-eu.lb.djnd.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: izvoli-nginx
                port:
                  number: 80
    - host: files.izvoli.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: izvoli-nginx
                port:
                  number: 80
